---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: bretfisher/wordsmith-api
    newName: ghcr.io/easlank/wordsmith-api
    newTag: stable-20230714-6746638
  - name: bretfisher/wordsmith-web
    newName: ghcr.io/easlank/wordsmith-web
    newTag: stable-20230714-5f473b5
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
